services:
  db:
    image: postgres:latest
    container_name: pizzeria-postgres-full
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pizzapass
      POSTGRES_DB: pizzeria
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pizzeria"]
      interval: 10s # Etwas mehr Zeit geben
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_full:/var/lib/postgresql/data

  backend:
    build: .
    container_name: pizzaria-backend-full
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8082:8081" # <--- Außen 8082 für dich, Intern bleibt es 8081
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=pizzeria
      - DB_USER=postgres
      - DB_PW=pizzapass

  adminer:
    image: adminer:latest
    container_name: pizzeria-adminer-full
    depends_on:
      - db
    ports:
      - "8086:8080" # Auch hier ein anderer Port, falls die Kollegen Adminer schon auf 8085 haben

volumes:
  postgres_data_full: