services:
  db:
    image: postgres:latest
    container_name: pizzeria-postgres-codespace
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pizzapass
      POSTGRES_DB: pizzeria

  adminer:
    image: adminer:latest
    container_name: pizzeria-adminer-codespace
    restart: always
    depends_on:
      - db
    ports:
      - "8085:8080"

  backend:
    build: .
    container_name: pizzaria-backend-codespace
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=codespace
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=pizzeria
      - DB_USER=postgres
      - DB_PW=pizzapass