services:
  db:
    image: postgres:latest
    container_name: pizzeria-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pizzapass
      POSTGRES_DB: pizzeria
    volumes:
      - postgres_data:/var/lib/postgresql

  adminer:
    image: adminer:latest
    container_name: pizzeria-adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8085:8080"

  backend:
    build: .
    container_name: pizzaria-backend
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      # Wir biegen localhost auf den Namen des DB-Services "db" um
      # Und wir nutzen den INTERNEN Port 5432 (nicht 5433)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pizzeria
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pizzapass

volumes:
  postgres_data:
