spring.application.name=Pizzeria

# --- DATASOURCE ---
# Diese Zeilen nutzen die Werte aus der YAML (DB_HOST, etc.). 
# Wenn keine Werte da sind (z.B. Start in IntelliJ), greifen die Werte nach dem Doppelpunkt.
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:pizzeria}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PW:pizzapass}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# --- INITIALISIERUNG ---
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=true

# --- SECURITY (JWT) ---
security.jwt.issuer=incrustwetrust-pizzeria
security.jwt.secret=f561925eec02dc41f5b0ae4a347e0d71f0ea1efa6daaf04cc64a7837017bc463092d68a4de0ac16f24a15b944f1db1f543835bdab604af0448ec9c11f6dfa7cc
security.jwt.expires-in-seconds=86400

# --- SWAGGER / DOCS ---
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# --- SERVER ---
server.port=8081
server.error.include-message=always

# --- LOGGING ---
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# --- MULTIPART ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
